export const ADD_INGREDIENT = "ADD_MORE_INGREDIENT"
export const REMOVE_INGREDIENT = "LESS_INGREDIENT"
export const INITIALIZE_INGREDIENTS = "FETCH_INGREDIENTS"

export const AUTHENTICATE_USER = "AUTHENTICATE_USER"
export const LOGIN_USER = "LOGIN_USER"